# micro's colourscheme, from the palette. ~/.config/micro/colorschemes/
# fig.micro links here, and settings.json names it.
#
# A running micro does not reread this. The next one does.
color-link default "{{ foreground }},{{ background }}"
color-link comment "{{ muted }}"
color-link constant "{{ magenta }}"
color-link constant.string "{{ green }}"
color-link constant.string.char "{{ green }}"
color-link constant.number "{{ orange }}"
color-link constant.bool "{{ magenta }}"
color-link identifier "{{ blue }}"
color-link identifier.class "{{ yellow }}"
color-link identifier.var "{{ foreground }}"
color-link statement "{{ red }}"
color-link preproc "{{ cyan }}"
color-link type "{{ yellow }}"
color-link type.keyword "{{ red }}"
color-link special "{{ orange }}"
color-link symbol "{{ foreground }}"
color-link symbol.brackets "{{ light_foreground }}"
color-link symbol.tag "{{ blue }}"
color-link underlined "{{ magenta }}"
color-link error "bold {{ bright_red }}"
color-link todo "bold {{ bright_yellow }}"
color-link diff-added "{{ green }}"
color-link diff-modified "{{ yellow }}"
color-link diff-deleted "{{ red }}"
color-link gutter-error "{{ bright_red }}"
color-link gutter-warning "{{ bright_yellow }}"
color-link line-number "{{ muted }},{{ background }}"
color-link current-line-number "{{ accent }},{{ background }}"
color-link cursor-line "{{ lighter_background }}"
color-link color-column "{{ lighter_background }}"
color-link indent-char "{{ muted }}"
color-link selection "{{ bright_foreground }},{{ selection }}"
color-link statusline "{{ background }},{{ accent }}"
color-link tabbar "{{ background }},{{ accent }}"
color-link scrollbar "{{ muted }}"
color-link divider "{{ muted }}"
